apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-jupyter-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  volumeName: jupyter-snapshot
  storageClassName: default
  volumeMode: Filesystem
